version: '3.8'

services:
  covins_dev:
    build:
      context: ../
      dockerfile: covins/sparx_docker/Dockerfile.dev
      args:
        - NR_JOBS=14
    container_name: covins_dev
    image: covins_dev_abs_layer
    volumes:
      - ../..:/root/covins_ws
    networks:
      - ros_net
    tty: true
    stdin_open: true
    command: bash  # or launch covins_backend/frontend if needed

  covins_ros2_wrapper:
    build:
      context: ../covins_ros2_wrapper
      dockerfile: docker/Dockerfile.ros2_wrapper
    image: covins_ros2_wrapper:latest
    container_name: covins_ros2_wrapper
    networks:
      - ros_net
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - ../covins_ros2_wrapper:/root/ros2_ws/src/covins_ros2_wrapper
      - ../..:/root/covins_ws:ro
    command: >
      ros2 launch covins_ros2_wrapper frontend_bridge.launch.py
    tty: true
    stdin_open: true
    depends_on:
      - covins_dev

networks:
  ros_net:
    name: ros_net
    driver: bridge
